### ISSUE TITLE
Muse 2017 Interface

### ISSUE THREAD

**Issue by RGPatterson** [j26design/PDF-Embedder#1]
I am trying to use PDF Embedder (Premium) in Muse 2017 and I don't see the interface described in your documentation.  All I get is the ability to specify the file to embed.  It embeds the file but I would like to alter the background and maybe even get rid of the normal PDF controls, since all I want to do is to display the file on the page and don't care about letting the use download or print it.

Maybe I didn't put the folders in the right place.  I put them in Library/WebServer/Documents since I read somewhere that that was the equivalent of the traditional "root" folder.  I don't have a "root" folder on my Mac running OS 10.11.6 (El Capitan).

**Comment by jp26jp** [comment]
There was an update sent out a few months ago that added these options. Check your spam folder and [send me an email](mailto:john@j-26.com) if you didn't get it.
